### ISSUE TITLE
Will it be work on .net core project ?

### ISSUE THREAD

**Issue by sagarraut0007** [BartoszKopec/MediawikiSharp_API#3]
Im kinda new to .Net. 
Can you please tell me, Whether this will be work on .net core projects ?

**Comment by BartoszKopec** [comment]
I checked the library in .Net Core ConsoleApp and it worked with no errors. If you will get some bugs - write Issue and I will fix it.

**Comment by sagarraut0007** [comment]
Thank You.

Thanks & Regards,
Sagar Raut | *Senior Software Engineer*
Mobile: + 91-9029200923 / 7767847666
Email: sagar.raut@jadeglobal.com | LinkedIn
<http://www.linkedin.com/in/raut-sagar>
